Code changes for upgrade to iptables-1.6.1.
1. Include time.h from xshared.h. This fixes the warning:
     external/iptables/iptables/xshared.h:89:36: error:
       declaration of 'struct timeval' will not be visible
       outside of this function [-Werror,-Wvisibility]
2. Make the iptables lock name a #define so we can specify it in
   Android.mk. Upstream hardcodes it to /run/xtables.lock, but
   /run does not exist on Android.

This CL only includes changes to upstream code so we can submit
it for upstream review.

Bug: 36108349
Test: see top of change stack.
Change-Id: I3d08f1a6b61eae1f3a24973b1cfa239280465e0f