Update patch set 1
Patch Set 1: Fails

Merges and builds fine in the open-source tree. However, while it merges fine in Google's internal master tree, it fails to compile there.

external/iptables/extensions/libip6t_owner.c: In function 'print_item':
external/iptables/extensions/libip6t_owner.c:147: error: format not a string literal and no format arguments

I've seen that before, where the toolchain wants printf("%s", label); instead of a naked printf(label)

Patch-set: 1